name: 部署到netlify

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: 通用的代码拉取
        uses: actions/checkout@v3
    
      - name: 安装nodejs 18.x版本
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: 安装依赖
        run: yarn
        
      - name: 打包发布
        run: yarn build

      - name: 开始拉取gitpages环境
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
        
