on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: 通用的代码拉取
        uses: actions/checkout@v3
    
      - name: 安装nodejs 18.x版本
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
