name: 部署到netlify

on:
  push:
    branches: 
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: 通用的代码拉取
        uses: actions/checkout@v3
    
      - name: 安装nodejs 18.x版本
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: 安装依赖
        run: yarn
        
      - name: 打包发布
        run: yarn build

      - name: 启用页面并提取有关站点的各种元数据
        uses: actions/configure-pages@v3

      - name: 上传页面工件
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        
